data_provider_name: cifar10
batch_size: 50
epochs: 100
early_stop_after_n_epochs: 10
optimizer_kwargs:
  learning_rate: 0.0001
layers:
- type: conv
  filter_count: 64
  kernel_length: 3
  strides: 1
  activation: leaky_relu
  assert_output_shape: [30, 30, 64]
- type: batch_norm
- type: conv
  filter_count: 128
  kernel_length: 3
  strides: 1
  activation: leaky_relu
  assert_output_shape: [28, 28, 128]
- type: batch_norm
- type: conv
  filter_count: 128
  kernel_length: 4
  strides: 2
  activation: leaky_relu
  assert_output_shape: [13, 13, 128]
- type: conv
  filter_count: 256
  kernel_length: 3
  strides: 1
  activation: leaky_relu
  assert_output_shape: [11, 11, 256]
- type: conv
  filter_count: 256
  kernel_length: 4
  strides: 1
  activation: leaky_relu
  assert_output_shape: [8, 8, 256]
- type: reshape
  shape: [50, 16384]
- type: dense
  units: 200
  activation: leaky_relu
  assert_output_shape: [200]
- type: dense
  units: 400
  activation: leaky_relu
  assert_output_shape: [400]
- type: dense
  units: 1024   # 32x32
  activation: sigmoid
  assert_output_shape: [1024]
- type: softmax_pred
  num_classes: 10
  id: softmax
- type: argmax
  id: prediction
loss:
  type: softmax_crossentropy
  softmax_id: softmax
prediction_id: prediction
