data_provider_name: cifar10
batch_size: 50
epochs: 100
early_stop_after_n_epochs: 10
optimizer_kwargs:
  learning_rate: 0.0005
layers:
- type: conv
  filter_count: 175  #256
  kernel_length: 3
  strides: 1
  activation: leaky_relu
  assert_output_shape: [30, 30, 175]
- type: batch_norm
- type: dropout
  rate: 0.5
  assert_output_shape: [30, 30, 175]
- type: conv
  filter_count: 175  #256
  kernel_length: 3
  strides: 1
  activation: leaky_relu
  assert_output_shape: [28, 28, 175]
- type: batch_norm
- type: dropout
  rate: 0.5
  assert_output_shape: [28, 28, 175]
- type: max_pool
  pool_size: [2, 2]
  strides: 2
  assert_output_shape: [14, 14, 175]
- type: conv
  filter_count: 350  #512
  kernel_length: 3
  strides: 1
  activation: leaky_relu
  assert_output_shape: [12, 12, 350]
- type: batch_norm
- type: conv
  filter_count: 350  #512
  kernel_length: 3
  strides: 1
  activation: leaky_relu
  assert_output_shape: [10, 10, 350]
- type: batch_norm
- type: reshape
  shape: [50, 35000]
- type: dense
  units: 450   # 700
  activation: leaky_relu
  assert_output_shape: [450]
- type: dense
  units: 900   # 1400
  activation: leaky_relu
  assert_output_shape: [900]
- type: dense
  units: 1024   # 32*32
  activation: sigmoid
  assert_output_shape: [1024]
- type: softmax_pred
  num_classes: 10
  id: softmax
- type: argmax
  id: prediction
loss:
  type: softmax_crossentropy
  softmax_id: softmax
prediction_id: prediction
