data_provider_name: smallnorb
batch_size: 50
epochs: 10
early_stop_after_n_epochs: 4
layers:
- type: reshape
  shape: [50, -1]
- type: dense
  units: 50
  activation: leaky_relu
- type: dense
  units: 50
  activation: leaky_relu
  assert_output_shape: [50]
- type: softmax_pred
  num_classes: 5
  id: softmax
- type: argmax
  id: prediction
loss:
  type: softmax_crossentropy
  softmax_id: softmax
important_metric:
  type: loss
  prediction_id: prediction
