data_provider_name: smallnorb
batch_size: 50
epochs: 100
early_stop_after_n_epochs: 10
layers:
- type: dense
  units: 50
  activation: leaky_relu
- type: batch_norm
- type: dense
  units: 50
  activation: leaky_relu
- type: softmax_pred
  num_classes: 5
  id: softmax
- type: argmax
  id: prediction
loss:
  type: softmax_crossentropy
  softmax_id: softmax
prediction_id: prediction
