data_provider_name: cifar10
batch_size: 50
epochs: 100
early_stop_after_n_epochs: 10
layers:
- type: conv
  filter_count: 256
  kernel_length: 9
  strides: 1
  activation: leaky_relu
  assert_output_shape: [24, 24, 256]
- type: caps_primary
  caps_count: 32
  caps_dim: 8
  kernel_length: 9
  strides: 2
  activation: leaky_relu
  assert_output_shape: [2048, 8]
- type: caps_out
  caps_count: 10
  caps_dim: 16
  assert_output_shape: [2048, 10, 16, 1]
- type: caps_routing
  iterations: 2
  id: caps_routing_out
  assert_output_shape: [1, 10, 16, 1]
- type: caps_pred
  id: caps_prediction
  assert_output_shape: []
- type: caps_masking
  routing_capsule_input_id: caps_routing_out
  assert_output_shape: [1, 10, 16, 1]
- type: reshape
  shape: [-1, 160]
- type: dense
  units: 512
  activation: leaky_relu
  assert_output_shape: [512]
- type: dense
  units: 1024
  activation: leaky_relu
  assert_output_shape: [1024]
- type: dense
  units: 3072   # 32 * 32 * 3
  activation: sigmoid
  assert_output_shape: [3072]
  id: decoder_output
loss:
  type: caps_net
  caps_routing_id: caps_routing_out
  decoder_output_id: decoder_output
prediction_id: caps_prediction




