data_provider_name: emnist
data_augmentation_name: mlp
batch_size: 50
epochs: 100
early_stop_after_n_epochs: 10
optimizer_kwargs:
  learning_rate: 0.0001
layers:
- type: conv
  filter_count: 256
  kernel_length: 5
  strides: 1
  activation: leaky_relu
  assert_output_shape: [24, 24, 256]
- type: batch_norm
- type: conv
  filter_count: 256
  kernel_length: 5
  strides: 1
  activation: leaky_relu
  assert_output_shape: [20, 20, 256]
- type: batch_norm
- type: max_pool
  pool_size: [2, 2]
  strides: 2
  assert_output_shape: [10, 10, 256]
- type: conv
  filter_count: 512
  kernel_length: 5
  strides: 1
  activation: leaky_relu
  assert_output_shape: [6, 6, 512]
- type: batch_norm
- type: conv
  filter_count: 512
  kernel_length: 3
  strides: 1
  activation: leaky_relu
  assert_output_shape: [4, 4, 512]
- type: batch_norm
- type: reshape
  shape: [50, 8192]
- type: dense
  units: 576
  activation: leaky_relu
- type: dense
  units: 1024
  activation: leaky_relu
- type: dense
  units: 1024
  activation: sigmoid
- type: softmax_pred
  num_classes: 47
  id: softmax
- type: argmax
  id: prediction
loss:
  type: softmax_crossentropy
  softmax_id: softmax
prediction_id: prediction
