data_provider_name: mtlsmallnorb
batch_size: 50
epochs: 100
early_stop_after_n_epochs: 10
optimizer_kwargs:
  learning_rate: 0.0001
layers:

- type: conv
  filter_count: 64
  kernel_length: 9
  strides: 1
  activation: leaky_relu
  assert_output_shape: [40, 40, 64]
- type: max_pool
  pool_size: [2, 2]
  strides: 2
  assert_output_shape: [20, 20, 64]
- type: reshape
  shape: [50, 25600]
- type: dense
  units: 80
  activation: leaky_relu
  assert_output_shape: [80]
- type: reshape
  shape: [50, 1, 5, 16, 1]
  id: fake_routing


# prediction
- type: softmax_pred
  num_classes: 10
  id: softmax
- type: argmax
  id: prediction

# begin decoder
- type: dense
  input_id: softmax
  units: 512
  activation: leaky_relu
  assert_output_shape: [512]
- type: dense
  units: 1024
  activation: leaky_relu
  assert_output_shape: [1024]
- type: dense
  units: 2304   # 48 * 48
  activation: sigmoid
  assert_output_shape: [2304]
  id: decoder_output

# begin azimith decoder
- type: dense
  input_id: softmax
  units: 512
  activation: leaky_relu
- type: dense
  units: 1
  activation: leaky_relu
  id: azimith_output

loss:
  type: mtl_caps_net
  caps_routing_id: fake_routing
  decoder_output_id: decoder_output
  azimith_output_id: azimith_output
  azimith_func: sin_squared
  alpha: 0.0005
  azimith_weight: 0.01
prediction_id: prediction

